export const EnumBackpackActions = {
  TOGGLE: 'TOGGLE',

  SELECTION: 'SELECTION',
  SELECTION_ADD: 'SELECTION_ADD',
  SELECTION_REMOVE: 'SELECTION_ADD',

  /**
   * FILE_?_INVOCATION: 'FILE_?_INVOCATION',
   * FILE_?: 'FILE_?',
   * FILE_?_SUCCESS: 'FILE_?_SUCCESS',
   * FILE_?_FAILURE: 'FILE_?_FAILURE',
   */

  FILE_NEW_INVOCATION: 'FILE_NEW_INVOCATION',
  FILE_NEW: 'FILE_NEW',
  FILE_NEW_SUCCESS: 'FILE_NEW_SUCCESS',
  FILE_NEW_FAILURE: 'FILE_NEW_FAILURE',

  FILE_OPEN_INVOCATION: 'FILE_OPEN_INVOCATION',
  FILE_OPEN: 'FILE_OPEN',
  FILE_OPEN_SUCCESS: 'FILE_OPEN_SUCCESS',
  FILE_OPEN_FAILURE: 'FILE_OPEN_FAILURE',

  FILE_CUT_INVOCATION: 'FILE_CUT_INVOCATION',
  FILE_CUT: 'FILE_CUT',
  FILE_CUT_SUCCESS: 'FILE_CUT_SUCCESS',
  FILE_CUT_FAILURE: 'FILE_CUT_FAILURE',

  FILE_PASTE_INVOCATION: 'FILE_PASTE_INVOCATION',
  FILE_PASTE: 'FILE_PASTE',
  FILE_PASTE_SUCCESS: 'FILE_PASTE_SUCCESS',
  FILE_PASTE_FAILURE: 'FILE_PASTE_FAILURE',

  FILE_RENAME_INVOCATION: 'FILE_RENAME_INVOCATION',
  FILE_RENAME: 'FILE_RENAME',
  FILE_RENAME_SUCCESS: 'FILE_RENAME_SUCCESS',
  FILE_RENAME_FAILURE: 'FILE_RENAME_FAILURE',

  FILE_DELETE_INVOCATION: 'FILE_DELETE_INVOCATION',
  FILE_DELETE: 'FILE_DELETE',
  FILE_DELETE_SUCCESS: 'FILE_DELETE_SUCCESS',
  FILE_DELETE_FAILURE: 'FILE_DELETE_FAILURE',

  FILE_SAVE_INVOCATION: 'FILE_SAVE_INVOCATION',
  FILE_SAVE: 'FILE_SAVE',
  FILE_SAVE_SUCCESS: 'FILE_SAVE_SUCCESS',
  FILE_SAVE_FAILURE: 'FILE_SAVE_FAILURE',

  LAYOUT_SELECT: 'LAYOUT_SELECT',
  LAYOUT_PREVIEW: 'LAYOUT_PREVIEW',
  LAYOUT_APPLY: 'LAYOUT_APPLY'
}
