export const EnumBackpackActions = {
  TOGGLE: 'BACKPACK__TOGGLE',

  SELECTION: 'BACKPACK__SELECTION',
  SELECTION_ADD: 'BACKPACK__SELECTION_ADD',
  SELECTION_REMOVE: 'BACKPACK__SELECTION_ADD',

  /**
   * FILE_?_INVOCATION: 'BACKPACK__FILE_?_INVOCATION',
   * FILE_?: 'BACKPACK__FILE_?',
   * FILE_?_SUCCESS: 'BACKPACK__FILE_?_SUCCESS',
   * FILE_?_FAILURE: 'BACKPACK__FILE_?_FAILURE',
   */

  FILE_NEW_INVOCATION: 'BACKPACK__FILE_NEW_INVOCATION',
  FILE_NEW: 'BACKPACK__FILE_NEW',
  FILE_NEW_SUCCESS: 'BACKPACK__FILE_NEW_SUCCESS',
  FILE_NEW_FAILURE: 'BACKPACK__FILE_NEW_FAILURE',

  FILE_OPEN_INVOCATION: 'BACKPACK__FILE_OPEN_INVOCATION',
  FILE_OPEN: 'BACKPACK__FILE_OPEN',
  FILE_OPEN_SUCCESS: 'BACKPACK__FILE_OPEN_SUCCESS',
  FILE_OPEN_FAILURE: 'BACKPACK__FILE_OPEN_FAILURE',

  FILE_CUT_INVOCATION: 'BACKPACK__FILE_CUT_INVOCATION',
  FILE_CUT: 'BACKPACK__FILE_CUT',
  FILE_CUT_SUCCESS: 'BACKPACK__FILE_CUT_SUCCESS',
  FILE_CUT_FAILURE: 'BACKPACK__FILE_CUT_FAILURE',

  FILE_PASTE_INVOCATION: 'BACKPACK__FILE_PASTE_INVOCATION',
  FILE_PASTE: 'BACKPACK__FILE_PASTE',
  FILE_PASTE_SUCCESS: 'BACKPACK__FILE_PASTE_SUCCESS',
  FILE_PASTE_FAILURE: 'BACKPACK__FILE_PASTE_FAILURE',

  FILE_RENAME_INVOCATION: 'BACKPACK__FILE_RENAME_INVOCATION',
  FILE_RENAME: 'BACKPACK__FILE_RENAME',
  FILE_RENAME_SUCCESS: 'BACKPACK__FILE_RENAME_SUCCESS',
  FILE_RENAME_FAILURE: 'BACKPACK__FILE_RENAME_FAILURE',

  FILE_DELETE_INVOCATION: 'BACKPACK__FILE_DELETE_INVOCATION',
  FILE_DELETE: 'BACKPACK__FILE_DELETE',
  FILE_DELETE_SUCCESS: 'BACKPACK__FILE_DELETE_SUCCESS',
  FILE_DELETE_FAILURE: 'BACKPACK__FILE_DELETE_FAILURE',

  FILE_SAVE_INVOCATION: 'BACKPACK__FILE_SAVE_INVOCATION',
  FILE_SAVE: 'BACKPACK__FILE_SAVE',
  FILE_SAVE_SUCCESS: 'BACKPACK__FILE_SAVE_SUCCESS',
  FILE_SAVE_FAILURE: 'BACKPACK__FILE_SAVE_FAILURE',

  LAYOUT_SELECT: 'BACKPACK__LAYOUT_SELECT',
  LAYOUT_PREVIEW: 'BACKPACK__LAYOUT_PREVIEW',
  LAYOUT_APPLY: 'BACKPACK__LAYOUT_APPLY'
}

export function toggleBackpack () {
  return { type: EnumBackpackActions.TOGGLE }
}
