export const EnumActActions = {
  ACT_NEW_INVOCATION: 'ACT_NEW_INVOCATION',
  ACT_NEW: 'ACT_NEW',
  ACT_NEW_SUCCESS: 'ACT_NEW_SUCCESS',
  ACT_NEW_FAILURE: 'ACT_NEW_FAILURE',

  ACT_RENAME_INVOCATION: 'ACT_RENAME_INVOCATION',
  ACT_RENAME: 'ACT_RENAME',
  ACT_RENAME_SUCCESS: 'ACT_RENAME_SUCCESS',
  ACT_RENAME_FAILURE: 'ACT_RENAME_FAILURE',

  ACT_DELETE_INVOCATION: 'ACT_DELETE_INVOCATION',
  ACT_DELETE: 'ACT_DELETE',
  ACT_DELETE_SUCCESS: 'ACT_DELETE_SUCCESS',
  ACT_DELETE_FAILURE: 'ACT_DELETE_FAILURE'
}
