export const EnumTaskActions = {
  TASK_NEW_INVOCATION: 'TASK_NEW_INVOCATION',
  TASK_NEW: 'TASK_NEW',
  TASK_NEW_SUCCESS: 'TASK_NEW_SUCCESS',
  TASK_NEW_FAILURE: 'TASK_NEW_FAILURE',

  TASK_RENAME_INVOCATION: 'TASK_RENAME_INVOCATION',
  TASK_RENAME: 'TASK_RENAME',
  TASK_RENAME_SUCCESS: 'TASK_RENAME_SUCCESS',
  TASK_RENAME_FAILURE: 'TASK_RENAME_FAILURE',

  TASK_DELETE_INVOCATION: 'TASK_DELETE_INVOCATION',
  TASK_DELETE: 'TASK_DELETE',
  TASK_DELETE_SUCCESS: 'TASK_DELETE_SUCCESS',
  TASK_DELETE_FAILURE: 'TASK_DELETE_FAILURE'
}
