import React, { Component } from 'react'
import 'sass/components/toc.scss'

class Toc extends Component {
  render () {
    return (
      <div className={'SideBar'}>
        TOC
        <div className='SideBar-content'>
          <div className='SideBar-group' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$0'>
            <h4 className='SideBar-groupTitle' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$0.0'>Quick Start</h4><a href='docs-overview.html' target='_self' className='SideBar-item SideBar-item--selected' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$0.1:$OVERVIEW'><span className='SideBar-itemText' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$0.1:$OVERVIEW.0'>Overview</span><span className='arrowBullet' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$0.1:$OVERVIEW.1'></span></a><a href='docs-tutorial.html' target='_self' className='SideBar-item' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$0.1:$TUTORIAL'><span className='SideBar-itemText' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$0.1:$TUTORIAL.0'>Tutorial</span><span className='arrowBullet' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$0.1:$TUTORIAL.1'></span></a><a href='docs-testing.html' target='_self' className='SideBar-item' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$0.1:$TESTING'><span className='SideBar-itemText' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$0.1:$TESTING.0'>Testing</span><span className='arrowBullet' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$0.1:$TESTING.1'></span></a><a href='docs-faq.html' target='_self' className='SideBar-item' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$0.1:$FAQ'><span className='SideBar-itemText' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$0.1:$FAQ.0'>FAQ</span><span className='arrowBullet' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$0.1:$FAQ.1'></span></a><a href='docs-troubleshooting.html' target='_self' className='SideBar-item' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$0.1:$TROUBLESHOOTING'><span className='SideBar-itemText' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$0.1:$TROUBLESHOOTING.0'>Troubleshooting</span><span className='arrowBullet' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$0.1:$TROUBLESHOOTING.1'></span></a></div>
          <div className='SideBar-group' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$1'>
            <h4 className='SideBar-groupTitle' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$1.0'>Top-Level API</h4><a href='docs-drag-source.html' target='_self' className='SideBar-item' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$1.1:$DRAG_SOURCE'><span className='SideBar-itemText' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$1.1:$DRAG_SOURCE.0'>DragSource</span><span className='arrowBullet' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$1.1:$DRAG_SOURCE.1'></span></a><a href='docs-drop-target.html' target='_self' className='SideBar-item' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$1.1:$DROP_TARGET'><span className='SideBar-itemText' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$1.1:$DROP_TARGET.0'>DropTarget</span><span className='arrowBullet' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$1.1:$DROP_TARGET.1'></span></a><a href='docs-drag-layer.html' target='_self' className='SideBar-item' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$1.1:$DRAG_LAYER'><span className='SideBar-itemText' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$1.1:$DRAG_LAYER.0'>DragLayer</span><span className='arrowBullet' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$1.1:$DRAG_LAYER.1'></span></a><a href='docs-drag-drop-context.html' target='_self' className='SideBar-item' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$1.1:$DRAG_DROP_CONTEXT'><span className='SideBar-itemText' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$1.1:$DRAG_DROP_CONTEXT.0'>DragDropContext</span><span className='arrowBullet' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$1.1:$DRAG_DROP_CONTEXT.1'></span></a></div>
          <div className='SideBar-group' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$2'>
            <h4 className='SideBar-groupTitle' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$2.0'>Connecting to DOM</h4><a href='docs-drag-source-connector.html' target='_self' className='SideBar-item' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$2.1:$DRAG_SOURCE_CONNECTOR'><span className='SideBar-itemText' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$2.1:$DRAG_SOURCE_CONNECTOR.0'>DragSourceConnector</span><span className='arrowBullet' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$2.1:$DRAG_SOURCE_CONNECTOR.1'></span></a><a href='docs-drop-target-connector.html' target='_self' className='SideBar-item' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$2.1:$DROP_TARGET_CONNECTOR'><span className='SideBar-itemText' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$2.1:$DROP_TARGET_CONNECTOR.0'>DropTargetConnector</span><span className='arrowBullet' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$2.1:$DROP_TARGET_CONNECTOR.1'></span></a></div>
          <div className='SideBar-group' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$3'>
            <h4 className='SideBar-groupTitle' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$3.0'>Monitoring State</h4><a href='docs-drag-source-monitor.html' target='_self' className='SideBar-item' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$3.1:$DRAG_SOURCE_MONITOR'><span className='SideBar-itemText' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$3.1:$DRAG_SOURCE_MONITOR.0'>DragSourceMonitor</span><span className='arrowBullet' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$3.1:$DRAG_SOURCE_MONITOR.1'></span></a><a href='docs-drop-target-monitor.html' target='_self' className='SideBar-item' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$3.1:$DROP_TARGET_MONITOR'><span className='SideBar-itemText' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$3.1:$DROP_TARGET_MONITOR.0'>DropTargetMonitor</span><span className='arrowBullet' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$3.1:$DROP_TARGET_MONITOR.1'></span></a><a href='docs-drag-layer-monitor.html' target='_self' className='SideBar-item' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$3.1:$DRAG_LAYER_MONITOR'><span className='SideBar-itemText' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$3.1:$DRAG_LAYER_MONITOR.0'>DragLayerMonitor</span><span className='arrowBullet' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$3.1:$DRAG_LAYER_MONITOR.1'></span></a></div>
          <div className='SideBar-group' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$4'>
            <h4 className='SideBar-groupTitle' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$4.0'>Backends</h4><a href='docs-html5-backend.html' target='_self' className='SideBar-item' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$4.1:$HTML5_BACKEND'><span className='SideBar-itemText' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$4.1:$HTML5_BACKEND.0'>HTML5</span><span className='arrowBullet' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$4.1:$HTML5_BACKEND.1'></span></a><a href='docs-test-backend.html' target='_self' className='SideBar-item' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$4.1:$TEST_BACKEND'><span className='SideBar-itemText' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$4.1:$TEST_BACKEND.0'>Test</span><span className='arrowBullet' data-reactid='.1onudyi3mrk.1.0.1.0.0.0.$4.1:$TEST_BACKEND.1'></span></a></div>
        </div>
      </div>
    )
  }
}

Toc.propTypes = {
}

export default Toc
